### ISSUE TITLE
Add_Input_field in UI.py

### ISSUE THREAD

**Issue by Takshay-Makadia** [MSTC-DA-IICT/HacktoberFest22-Play-with-Python#6]
Following enhancements are needed :

1. Edit the UI.py file in Grammer_Tools folder to take user input as _text_ entered in a text box as well as add the functionality to take input as a .txt file.
2. Additionally, set proper dimensions for the tkinter window and properly arrange all the buttons and text boxes as per your creativity.
3. Also create a region in the tkinter window itself to display the answers returned by the functions in main.py

**Comment by naisargi1101** [comment]
I would like to contribute to this issue

**Comment by Takshay-Makadia** [comment]
Sure @naisargi1101, go ahead!!

**Comment by naisargi1101** [comment]
I have generated the pull request. Kindly verify.
![output](https://user-images.githubusercontent.com/61086786/194933221-2d43361e-de1b-4983-86e4-6de3559834c6.PNG)

**Comment by Takshay-Makadia** [comment]
Pull request #10 was merged for this issue and the issue is resolved.
