### ISSUE TITLE
Add new features in Grammer_Tools

### ISSUE THREAD

**Issue by Takshay-Makadia** [MSTC-DA-IICT/HacktoberFest22-Play-with-Python#8]
Like finding nouns in a text file, add other features like finding pronouns, adverbs etc. using spacy library.
_Note_ : Add at least 4 new features.

**Comment by rockysaikia730** [comment]
I have added the features and buttons. Kindly consider it.

**Comment by Takshay-Makadia** [comment]
Everyone please note that #9 has not been solved in this commit. Only new features were added in this particular commit.
